### ISSUE TITLE
Current status for this project?

### ISSUE THREAD

**Issue by tomasruud** [Giuseppe-Mazzapica/Cortex#25]
I'm just wondering what the current status for this project is. 

I've been using it for some smaller and larger projects recently and I'm really starting to like it. The only drawback that I can see, is that this project still seems to be in alpha. From what I can tell, there are some undocumentet features (like the controllers), which makes me worried things might be changing.

**Comment by gmazzap** [comment]
Hi @tomasruud ,

The project is mainatained. I have (and "we have", at company I work for) projects using this, so this is not going to be abandoned anytime soon.

If you, or us, or anyone else find a bug, it will be addressed. There are plans for new features, which are on hold for lack of time, but existing features are going nowhere.

Yes, the project is not in a stable phase yet, but I'm sticking with semantic versioning which means I'm not going to break backward compatibility before version 2.0, so if you require via Composer with something like `~1.0.0`, or even `^1.0`, you can be sure you can rely on what you have now. Things might be added, but existing things won't break.

**Comment by tomasruud** [comment]
That's reassuring! Do you know when you might continue working on new features?

**Comment by gmazzap** [comment]
@tomasruud Honestly no. Because job + family I don't really have much time for OS these days.

Inpsyde (company I work for) is right now sponsoring me on working on another OS project ([WP Starter](https://github.com/wecodemore/wpstarter), for the records). When that is done (plan is end of november) I will try to convince them sponsoring Cortex as well, but even if Inpsyde accepts, work must be coordinated with company work... so, really, no idea, but don't expect anything before 2019.

However, I'm very open to contributions, so if someone will send PR, I'll be very happy to review, discuss and merge... Even contributions on documentation is **very** welcome.

**Comment by tomasruud** [comment]
Yeah, I totally get that. I don't really have much time to contribute either, but maybe if you could put up some of your plans for new features, I or someone else might find time to help you out.
